Feature/client registration
SofieTorch/taxi-segurito-flutter-version pull request #9
Opened 2021-10-03 14:56 UTC by JoseeCarlos

2021-10-04 20:50 UTC, SofieTorch requested changes

2021-10-05 03:28 UTC, SofieTorch requested changes

2021-10-06 14:41 UTC, SofieTorch requested changes

2021-10-06 14:41 UTC, SofieTorch commented on lib/models/user.dart
> +  late int iduser;
pregunta, si `Person` ya tiene el id, aún es necesario ponerlo en `User`? 🤔

2021-10-06 14:41 UTC, SofieTorch commented on lib/models/user.dart
> +  late int iduser;
también en `ClientUser` 🤔

2021-10-06 15:34 UTC, JoseeCarlos commented on lib/models/user.dart
> +  late int iduser;
ahora lo quito :(

2021-10-06 15:57 UTC, SofieTorch approved these changes
listooooo :'D

2021-10-06 15:57 UTC, merged